CREATE TABLE IF NOT EXISTS users(
                      user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      login varchar NOT NULL,
                      email varchar NOT NULL,
                      name varchar,
                      birhday date NOT NULL);

CREATE TABLE IF NOT EXISTS friends(
                        user_id INTEGER references users(user_id),
                        friend_id INTEGER,
                        PRIMARY KEY(user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa_rate(
                         mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         name varchar
);

CREATE TABLE IF NOT EXISTS films(
                      film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar NOT NULL,
                      description varchar NOT NULL,
                      release_date date NOT NULl,
                      duration INTEGER NOT NULL,
                      mpa_id INTEGER references mpa_rate(mpa_id)
);

CREATE TABLE IF NOT EXISTS likes (
                       film_id INTEGER references films(film_id),
                       user_id INTEGER references users(user_id),
                       PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre(
                      genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar
);

CREATE TABLE IF NOT EXISTS film_genre(
                           film_id INTEGER references films(film_id),
                           genre_id INTEGER references genre(genre_id),
                           PRIMARY KEY (film_id, genre_id));